version: '3'

services:

  dotnetcore:
    image: pbolkas/back_end:0.0.2
    ports:
      - 80:80
    env_file:
      - local.env

  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    env_file: 
      - local.env
  
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    env_file:
      - local.env