version: '3'

services:

  dotnetcore:
    image: pbolkas/back_end:latest
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    env_file: 
      - local.env
    volumes:
    - my-datavolume:/var/lib/mysql

  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    env_file:
      - local.env
    volumes:
    - playlists-mongo-volume:/data/db
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  my-datavolume:
  playlists-mongo-volume: