version: '3'

services:

  dotnetcore:
    image: pbolkas/back_end:0.0.3
    ports:
      - 80:80

  mysql:
    image: mysql:latest
    ports: 
      - 3306:3306
    env_file: 
      - local.env
    volumes:
    - my-datavolume:/var/lib/mysql
  
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    env_file:
      - local.env

volumes:
  my-datavolume: