version: '3'

services:

  dotnetcore:
    image: <image-path>:<tag>
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  mongodb:
    image: mongodb:latest
    ports: 
      - 27017:27017
    env_file:
      - local.env
    volumes:
      - mongo-data:/home/mongo/data

  volumes:
    mongo-data:
     