version: '3'

services:
  
  dotnetcore:
    image: 814311800761.dkr.ecr.us-east-2.amazonaws.com/playlists/back_end:latest
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  mongodb:
    image: mongodb:latest
    ports: 
      - 27017:27017
    env_file:
      - staging.env
    volumes:
      - mongo-data:/home/mongo/data

  volumes:
    mongo-data:
     